import requests
import sys
import io

sys.stdout = io.TextIOWrapper(sys.stdout.buffer,encoding='utf-8') #改变标准输出的默认编码


#登录时需要POST的数据
data = {'__VIEWSTATE': 'dDw1NjkwNTA3NjQ7dDw7bDxpPDE+Oz47bDx0PDtsPGk8Mz47aTwxND47aTwxNz47PjtsPHQ8cDxsPFZpc2libGU7PjtsPG88Zj47Pj47Oz47dDxwPDtwPGw8b25jbGljazs+O2w8d2luZG93LmNsb3NlKClcOzs+Pj47Oz47dDxwPGw8aW5uZXJodG1sOz47bDxcPHRhYmxlIHdpZHRoPScxMDAlJyBib3JkZXI9JzAnIGNlbGxzcGFjaW5nPScwJyBjZWxscGFkZGluZz0nMCdcPlw8dHJcPlw8dGRcPlw8YSB0YXJnZXQ9X2JsYW5rICBocmVmPSdqd2dnY2suYXNweD9mYnNqPTIwMTAtMDQtMTQrMTMlM2E0OSUzYTM3JmdnYnQ9JWNlJWY3JWQ2JWIwJWQyJWI1JWQ1JWZkJWI3JWJkJWJkJWNjJWNlJWYxJWNmJWI1JWNkJWIzJWJmJWNkJWJiJWE3JWI2JWNiJWIwJWIyJWQ3JWIwJWIzJWNjJWQwJWYyJWNmJWMyJWQ0JWQ4JkNvZGVGbGFnPSVjZCVhOCVkNiVhYSVjZSVjNCViYyVmZSdcPlw8c3Bhblw+MjAxMC00LTE0XDwvc3Bhblw+IOilv+iBjOS4muato+aWueaVmeWKoeezu+e7n+WuouaIt+err+Wuieijheeoi+W6j+S4i+i9vSjpgJrnn6Xmlofku7YpXDwvYVw+XDwvdGRcPlw8L3RyXD5cPHRyXD5cPHRkXD5cPGEgdGFyZ2V0PV9ibGFuayAgaHJlZj0nandnZ2NrLmFzcHg/ZmJzaj0yMDExLTEyLTE1KzExJTNhMzUlM2EzOSZnZ2J0PSViZCVjYyVjZSVmMSViOSVkYyVjMCVlZCVkMCVjNSVjZiVhMiVjZiViNSVjZCViMyViZCVjYyVjYSVhNiVjZCVmOCVjOSVjZiViMyVjOSViYyVhOCViNSVjNyVjMiViYyViMiVkOSVkNyVmNyVkNiViOCVjNCVjZiZDb2RlRmxhZz0lY2QlYTglZDYlYWElY2UlYzQlYmMlZmUnXD5cPHNwYW5cPjIwMTEtMTItMTVcPC9zcGFuXD4g5pWZ5Yqh566h55CG5L+h5oGv57O757uf5pWZ5biI572R5LiK5oiQ57up55m75b2V5pON5L2c5oyH5Y2XKOmAmuefpeaWh+S7tilcPC9hXD5cPC90ZFw+XDwvdHJcPlw8dHJcPlw8dGRcPlw8YSB0YXJnZXQ9X2JsYW5rICBocmVmPSdqd2dnY2suYXNweD9mYnNqPTIwMTItMDEtMDkrMTUlM2EwMiUzYTU3JmdnYnQ9MjAxMS0yMDEyJWQxJWE3JWM0JWVhJWI1JWRhJWQyJWJiJWQxJWE3JWM2JWRhJWJiJWJhJWJmJWJjJWNkJWIzJWJjJWM2JWIxJWVkJkNvZGVGbGFnPSVjZCVhOCVkNiVhYSVjZSVjNCViYyVmZSdcPlw8c3Bhblw+MjAxMi0xLTlcPC9zcGFuXD4gMjAxMS0yMDEy5a2m5bm056ys5LiA5a2m5pyf57yT6ICD57uf6K6h6KGoKOmAmuefpeaWh+S7tilcPC9hXD5cPC90ZFw+XDwvdHJcPlw8dHJcPlw8dGRcPlw8YSB0YXJnZXQ9X2JsYW5rICBocmVmPSdqd2dnY2suYXNweD9mYnNqPTIwMTItMDYtMjgrMTAlM2EyNSUzYTIzJmdnYnQ9MjAxMS0yMDEyJWI1JWRhJWI2JWZlJWQxJWE3JWM2JWRhJWJiJWJhJWJmJWJjJWNkJWIzJWJjJWM2JWIxJWVkJkNvZGVGbGFnPSVjZCVhOCVkNiVhYSVjZSVjNCViYyVmZSdcPlw8c3Bhblw+MjAxMi02LTI4XDwvc3Bhblw+IDIwMTEtMjAxMuesrOS6jOWtpuacn+e8k+iAg+e7n+iuoeihqCjpgJrnn6Xmlofku7YpXDwvYVw+XDwvdGRcPlw8L3RyXD5cPC90YWJsZVw+XDxzY3JpcHQgdHlwZT0ndGV4dC9qYXZhc2NyaXB0J1w+dmFyIG9NYXJxdWVlID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ21xJylcO3ZhciBpTGluZUhlaWdodCA9IDQwXDt2YXIgaUxpbmVDb3VudCA9IDRcO3ZhciBpU2Nyb2xsQW1vdW50ID0gMVw7IGZ1bmN0aW9uIHJ1bigpe29NYXJxdWVlLnNjcm9sbFRvcCArPSBpU2Nyb2xsQW1vdW50XDtpZiAoIG9NYXJxdWVlLnNjcm9sbFRvcCA9PSBpTGluZUNvdW50ICogaUxpbmVIZWlnaHQgKXtvTWFycXVlZS5zY3JvbGxUb3AgPSAwXDt9aWYgKCBvTWFycXVlZS5zY3JvbGxUb3AgJSBpTGluZUhlaWdodCA9PSAwICkge3dpbmRvdy5zZXRUaW1lb3V0KCAncnVuKCknLCAyMDAwIClcO30gZWxzZSB7d2luZG93LnNldFRpbWVvdXQoICdydW4oKScsIDUwIClcO319b01hcnF1ZWUuaW5uZXJIVE1MICs9IG9NYXJxdWVlLmlubmVySFRNTFw7d2luZG93LnNldFRpbWVvdXQoICdydW4oKScsIDIwMDAgKVw7XDwvc2NyaXB0XD47Pj47Oz47Pj47Pj47bDxpbWdETDs+PsECbgUOMHlkRI3A8RjMunfF9Mrv',
'tbYHM': 'XXXXXXX',
'tbPSW': 'XXXX',
'TextBox3': '3ldu',
'RadioButtonList1': '(unable to decode value)',
'imgDL.x': '2',
'imgDL.y': '9'}
#验证码
codeurl = 'XXXXXXXXXXXXXXXXXXXXXXXXX'
valcode = requests.get(codeurl)

f = open('valcode.png', 'wb')
    # 将response的二进制内容写入到文件中
f.write(valcode.content)
    # 关闭文件流对象
f.close()
code = input('请输入验证码：')
data["TextBox3"] = str(code)
#设置请求头
headers = {'User-agent':'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36'}

#登录时表单提交到的地址（用开发者工具可以看到）
login_url = 'XXXXXXXXXXXXXXXXXXXXXXXXX'

#构造Session
session = requests.Session()

#在session中发送登录请求，此后这个session里就存储了cookie
#可以用print(session.cookies.get_dict())查看
resp = session.post(login_url, data)

#登录后才能访问的网页
url = 'XXXXXXXXXXXXXXXXXXXXXXXXX'

#发送访问请求
resp = session.get(url)

print(resp.content)